### ISSUE TITLE
Question about image_size in 'Template-BBDM'.yaml

### ISSUE THREAD

**Issue by HaHaFish1014** [xuekt98/BBDM#54]
Thank you for your great work and share your code!
I have a question about the image_size in 'Template-BBDM'.yaml. When i use the 'Template-LBBDM-f8'.yaml to train in my own datasets for colorization, i found that the results of sample_to_eval are very strange. I solved it by using the 'Template-BBDM'.yaml. However, using 'Template-BBDM'.yaml only generate 64*64 images. I want to generate 128*128 and 256*256 images. What should i do to modify the yaml setting? Can i just simply modify data:image_size and Unet:image_size?
Hope for your reply.

**Comment by sumit171993** [comment]
Hi @HaHaFish1014 , I am unable to access the pretrained model CelebHQ , since I unable to make my account on the baidu link, since I am from India, please the pretrained weights which you are using for fine tuning on your dataset , if possible by some google drive link if you are doing so, otherwise i need to train from scratch, but i have limited images right now for training i.e., 2101 only. Regarding your question, I am using 256 x256 images for training and for unet using 64 x64, i think we shouldnot change the Unet dimensions. Thanks and Regards, Sumit

**Comment by HaHaFish1014** [comment]
> Hi @HaHaFish1014 , I am unable to access the pre-trained model CelebHQ since I am unable to make my account on the Baidu link since I am from India; please provide the pre-trained weights that you are using for fine-tuning your dataset; if possible by some google drive link if you are doing so. Otherwise, I need to train from scratch, but I have limited images right now for training, i.e., 2101 only. Regarding your question, I am using 256 x256 images for training, and for Unet using 64 x64, I think we should not change the Unet dimensions. Thanks and Regards, Sumit, This is my emailID: [ee20d042@smail.iitm.ac.in](mailto:ee20d042@smail.iitm.ac.in)

Thank you for your advice!
I did not use the pre-trained weights. I used my own dataset to train from beginning.
About pre-trained weights, you should ask the author because i think i do not have the authority to disseminate the pre-trained weights.
May i ask you if you use the  'Template-BBDM.yaml' to train? How did you use 256*256 images for training? I cant train if i use 256*256 images as input. Only modify the 'Template-BBDM.yaml' setting can solve it, but i am worried that it will break the proper function of the attention layers in Unet.

**Comment by HaHaFish1014** [comment]
I found that the author has already answered a similar question in #8 .

**Comment by sumit171993** [comment]
Thank You So much!!!

Regards,
Sumit
